[build]
  publish = "./"
  command = ""
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  external_node_modules = ["nodemailer"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
